import sql from './utils/db';

export default async () => {
  try {
    console.log('Migrating database...');
    
    await sql`
      create table if not exists public.credly_submissions (
        id bigint generated by default as identity primary key,
        name text not null,
        badges jsonb not null default '[]'::jsonb,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    await sql`
      create table if not exists public.softwares (
        id bigint generated by default as identity primary key,
        name text not null,
        description text,
        icon_url text,
        download_url text not null,
        category text not null default 'Utility',
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    await sql`
      create table if not exists public.tutorials (
        id bigint generated by default as identity primary key,
        title text not null,
        description text,
        thumbnail_url text,
        video_url text not null,
        category text not null default 'General',
        duration text not null default '00:00',
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    await sql`
      create table if not exists public.repair_requests (
        id bigint generated by default as identity primary key,
        customer_name text not null,
        unit_model text not null,
        issue text not null,
        lcd_grade text,
        lcd_link text,
        lcd_expected_price numeric,
        labor_fee numeric not null default 200,
        status text not null default 'pending',
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    await sql`ALTER TABLE public.repair_requests ADD COLUMN IF NOT EXISTS lcd_link text;`;
    await sql`ALTER TABLE public.repair_requests ADD COLUMN IF NOT EXISTS lcd_expected_price numeric;`;

    await sql`
      create table if not exists public.anime (
        id bigint generated by default as identity primary key,
        title text not null,
        description text,
        cover_image text,
        banner_image text,
        genre text[] default '{}',
        status text default 'ongoing',
        rating numeric default 0,
        total_episodes integer default 0,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    await sql`
      create table if not exists public.episodes (
        id bigint generated by default as identity primary key,
        anime_id bigint references public.anime(id) on delete cascade,
        episode_number integer not null,
        title text,
        thumbnail_url text,
        video_url text,
        video_url_2 text,
        video_url_dub text,
        video_url_dub_2 text,
        season_number integer default 1,
        intro_start integer default 0,
        intro_end integer default 0,
        outro_start integer default 0,
        outro_end integer default 0,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        unique(anime_id, episode_number, season_number)
      );
    `;

    await sql`ALTER TABLE public.episodes ADD COLUMN IF NOT EXISTS video_url_2 text;`;
    await sql`ALTER TABLE public.episodes ADD COLUMN IF NOT EXISTS video_url_dub text;`;
    await sql`ALTER TABLE public.episodes ADD COLUMN IF NOT EXISTS video_url_dub_2 text;`;

    await sql`
      create table if not exists public.device_prices (
        id bigint generated by default as identity primary key,
        unit_model text not null unique,
        lcd_aaa_price numeric not null,
        lcd_original_price numeric not null,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    return new Response(JSON.stringify({ message: 'Migration complete! Table created.' }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });
  } catch (error: unknown) {
    console.error('Migration failed:', error);
    return new Response(JSON.stringify({ error: `Migration failed: ${error instanceof Error ? error.message : String(error)}` }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};
