
-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Drop old tables if they exist (Destructive!)
drop table if exists public.orders;
drop table if exists public.products;

-- Anime Table
create table public.anime (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  cover_image text,
  banner_image text,
  genre text[], -- Array of genres
  status text check (status in ('ongoing', 'completed', 'upcoming')),
  rating numeric default 0,
  total_episodes integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Episodes Table
create table public.episodes (
  id bigint generated by default as identity primary key,
  anime_id bigint references public.anime(id) on delete cascade,
  episode_number integer not null,
  title text,
  thumbnail_url text,
  video_url text, -- For now, direct link or embed URL
  duration integer, -- in seconds
  season_number integer default 1,
  intro_start integer default 0,
  intro_end integer default 0,
  outro_start integer default 0,
  outro_end integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(anime_id, episode_number, season_number)
);

-- System Settings Table (Keep existing)
create table if not exists public.system_settings (
  key text primary key,
  value text,
  description text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Apps Table (Keep existing app request feature as users might still want it, or delete? Keeping for now based on user request "change shop", implies keeping other parts)
create table if not exists public.apps (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  download_url text,
  version text,
  category text,
  downloads integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- App Requests Table (Keep existing)
create table if not exists public.app_requests (
  id bigint generated by default as identity primary key,
  app_name text not null,
  app_description text,
  requester_email text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Credly Submissions Table
create table if not exists public.credly_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  badges jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Default Settings
insert into public.system_settings (key, value, description)
values ('site_name', 'GMZN Anime', 'Name of the streaming site')
on conflict (key) do nothing;
