import postgres from 'postgres';
import dotenv from 'dotenv';

dotenv.config();

const sql = postgres(process.env.DATABASE_URL!, { ssl: 'require' });

async function migrate() {
  try {
    console.log('Migrating database...');
    
    await sql`
      create table if not exists public.credly_submissions (
        id bigint generated by default as identity primary key,
        name text not null,
        badges jsonb not null default '[]'::jsonb,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    console.log('Migration complete!');
    process.exit(0);
  } catch (error) {
    console.error('Migration failed:', error);
    process.exit(1);
  }
}

migrate();
