
import postgres from 'postgres';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const dbUrl = process.env.DATABASE_URL;

if (!dbUrl) {
    console.error('DATABASE_URL is not defined');
    process.exit(1);
}

const sql = postgres(dbUrl, { ssl: 'require' });

async function migrate() {
    try {
        console.log('Starting migration...');

        // Softwares Table
        await sql`
            CREATE TABLE IF NOT EXISTS public.softwares (
                id bigint generated by default as identity primary key,
                name text not null,
                description text,
                icon_url text,
                download_url text,
                category text,
                created_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
        `;
        console.log('Created table: softwares');

        // Tutorials Table
        await sql`
            CREATE TABLE IF NOT EXISTS public.tutorials (
                id bigint generated by default as identity primary key,
                title text not null,
                description text,
                thumbnail_url text,
                video_url text, -- Or link to article
                category text,
                duration text,
                created_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
        `;
        console.log('Created table: tutorials');

        // Developer Profile Table
        await sql`
            CREATE TABLE IF NOT EXISTS public.developer_profile (
                id bigint generated by default as identity primary key,
                name text not null,
                bio text,
                avatar_url text,
                role text,
                social_links jsonb, -- { "github": "url", "twitter": "url" }
                updated_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
        `;
        console.log('Created table: developer_profile');

        // Insert default developer profile if not exists
        await sql`
            INSERT INTO public.developer_profile (name, bio, role, social_links)
            SELECT 'MCK', 'Full Stack Developer', 'Lead Developer', '{"github": "https://github.com", "website": "https://example.com"}'::jsonb
            WHERE NOT EXISTS (SELECT 1 FROM public.developer_profile);
        `;
        console.log('Seeded default developer profile');

    } catch (error) {
        console.error('Migration failed:', error);
    } finally {
        await sql.end();
    }
}

migrate();
